version: '3.1'

networks:
  RLT-test:

services:
  mongo:
    image: mongo
    env_file: .env
    restart: always
    container_name: "mongo"
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ADMIN_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ADMIN_PASSWORD}
    networks:
      - RLT-test

  mongo-express:
    image: mongo-express
    env_file: .env
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_ADMIN_NAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_ADMIN_NAME}:${DB_ADMIN_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - RLT-test

  bot:
    build:
      context: ../
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    container_name: "bot"
    ports:
      - '8080:8080'
    volumes:
      - ../:/app
    depends_on:
      - mongo
      - mongo-express
    networks:
      - RLT-test
